### ISSUE TITLE
Review #2 - Detalle cuando no jugas ninguna mano

### ISSUE THREAD

**Issue by FacundoEG** [rikochet87/desafio-m5#2]
Hola @rikochet87 ! como estas? agrego algunas cosas para revisar aparte de las que te mencionaron en el issue #1 

Fíjate que la primera vez que jugas, si no elegís ninguna jugada te vuelve a enviar a la pagina de instrucciones. Pero después de esa primera jugada (por ejemplo la segunda vez) si no elegís ninguna mano el contador te queda en "1" y el juego no avanza.
![image](https://user-images.githubusercontent.com/79592789/162773681-91214dda-b53e-46f6-ba89-78b13eb45543.png)

Sacando ese detalle veo que esta muy bien la webapp, así que de mi parte te lo voy a dar como aprobado pero te dejo eso para que mejores si? 

Te mando un saludo y te deseo lo mejor para el próximo modulo!

**Comment by rikochet87** [comment]
Facu muchas gracias! si hay cosas que no me quedaron claras de este modulo, me costo muchísimoy a pesar que lo pasé aun no lo tengo claro. Tendría que hacerlo de nuevo quizás. Gracias!

**Comment by FacundoEG** [comment]
No pasa nada! es un modulo bastante complicado así que tómatelo con calma, cualquier cosita podes consultar en el canal de discord! saludos!
